<table border="0" cellpadding="0" cellspacing="0" width="100%" class="mcnTextBlock">
    <tbody class="mcnTextBlockOuter">
        <tr>
            <td valign="top" class="mcnTextContent" style="padding-top:9px; padding-right: 18px; padding-bottom: 9px; padding-left: 18px;">
                Cliente: <strong>{{booking.roomDistribution[0].paxList[0].lastName}} {{booking.roomDistribution[0].paxList[0].name}}</strong>
            </td>
        </tr>
    </tbody>
</table>