<!-- Services  -->
<script src="/js/angular/services/httpsvc.js?v={? appversion ?}"></script>
<!-- dependencies -->
<script src="/js/angular/vendor/checklist/checklist-model.js?v={? appversion ?}"></script>
<script src="/js/angular/vendor/toaster/toaster.js?v={? appversion ?}"></script>
<script src="/js/angular/vendor/bootstrap-slider-master/dist/bootstrap-slider.min.js?v={? appversion ?}"></script>
<script src="/js/libs/angular-bootstrap-lb.js?v={? appversion ?}"></script>
<!-- Directives -->
<script src="/js/angular/directives/autocomplete.js?v={? appversion ?}"></script>
<script src="/js/angular/vendor/ui-bootstrap/ui-bootstrap-tpls-0.14.3.min.js"></script> 
