<!-- sentry configs -->

<script src="https://cdn.ravenjs.com/2.3.0/angular/raven.min.js"></script>
 <script>Raven.config('http://d65ff222640a4b2a82fe00cf6a8a0be9@sentry.teamrockmotion.com/27').install();</script>


<!-- sentry configs -->

<!-- Include all compiled plugins (below), or include individual files as needed -->
<script src="/components/angular-bindonce/bindonce.min.js"></script>
<script src="/js/angular/servivuelo/servivuelo.module.js?v={? appversion ?}"></script>
<script src="/js/angular/servivuelo/services/searchFlight.service.js?v={? appversion ?}"></script>
<script src="/js/angular/servivuelo/services/sharedFlight.service.js?v={? appversion ?}"></script>
<script src="/js/angular/servivuelo/controllers/searchFlight.controller.js?v={? appversion ?}"></script>
<script src="/js/angular/servivuelo/controllers/prepareFlight.controller.js?v={? appversion ?}"></script>
<script src="/js/angular/servivuelo/controllers/modal.controller.js?v={? appversion ?}"></script>
<script src="/js/angular/servivuelo/controllers/modal.rates.controller.js?v={? appversion ?}"></script>
<script src="/js/angular/servivuelo/directives/flightlist.directive.js?v={? appversion ?}"></script>
<script src="/js/angular/servivuelo/directives/infoVuelo.directive.js?v={? appversion ?}"></script>
<script src="/js/angular/servivuelo/directives/preparebooking.directive.js?v={? appversion ?}"></script>
<script src="/js/angular/servivuelo/directives/itinerarioVuelo.directive.js?v={? appversion ?}"></script>
<script src="/js/angular/servivuelo/directives/hotel.directive.js?v={? appversion ?}"></script>
<script src="/js/angular/servivuelo/directives/actividadesinfo.directive.js?v={? appversion ?}"></script>
<script src="/js/angular/servivuelo/directives/haveflight.directive.js?v={? appversion ?}"></script>
<script src="/js/angular/servivuelo/directives/precioTerrestre.directive.js?v={? appversion ?}"></script>
<script src="/js/angular/servivuelo/filters/spanishDate.directive.js?v={? appversion ?}"></script>
<script src="/js/angular/servivuelo/filters/person.directive.js?v={? appversion ?}"></script>
<script src="/js/angular/servivuelo/filters/nl2br.directive.js?v={? appversion ?}"></script>
<script src="/components/ui-select/dist/select.js?v={? appversion ?}"></script>
<script src="/components/angularjs-slider/dist/rzslider.min.js?v={? appversion ?}"></script>
<script src="/components/moment/moment.js?v={? appversion ?}"></script>
<script src="/components/angular-moment/angular-moment.js?v={? appversion ?}"></script>
<script src="/components/moment/locale/es.js?v={? appversion ?}"></script>
