var async = require('async');
module.exports = function (conf) {
    return {
        book : [
            async.apply(require('./book.inputvalidation'), conf),
            require('./book.readyprocess'),
            require('./getcurrencyexchanges'),
            require('./getcountries'),
            require('./getproduct'),
            require('./getaffiliate'),
            require('./getdmc'),
            require('./getquote'),
            require('./book.signup'),
            require('./book.datavalidation'),
            require('./book.builddates'),
            require('./book.newinstance'),
            require('./book.rooms'),
            require('./book.setpricing'),
            require('./book.saveproduct'),
            require('./book.changecurrency'),
            require('./book.firststory'),
            require('./book.savebooking'),
            require('./hermes'),
            //require('./book.pushmails'),
            require('./book.newcommit')
        ],
        budget: [
            async.apply(require('./budget.inputvalidation'), conf),
            require('./book.readyprocess'),
            require('./getcurrencyexchanges'),
            require('./getcountries'),
            require('./getproduct'),
            require('./getaffiliate'),
            require('./getdmc'),
            require('./getquote'),
            require('./budget.signup'),
            require('./book.datavalidation'),
            require('./book.builddates'),
            require('./book.newinstance'),
            require('./book.rooms'),
            require('./book.setpricing'),
            require('./budget.saveproduct'),
            require('./book.changecurrency'),
            require('./budget.savebudget'),
            require('./budget.newcommit')
        ],
        pay: [
            async.apply(require('./pay.datavalidation'), conf),
            require('./pay.readyprocess'),
            require('./getcurrencyexchanges'),
            require('./getbooking'),
            require('./book.payments'),
            require('./book.addstory'),
            require('./savebooking'),
            require('./hermes'),
            require('./book.pushmails'),
            require('./pay.commit')
        ],
        pricing: [
            async.apply(require('./pricing.datavalidation'), conf),
            require('./pricing.readyprocess'),
            require('./getaffiliate'),
            require('./getbooking'),
            require('./pricing.apply'),
            require('./book.addstory'),
            require('./savebooking'),
            require('./hermes'),
            require('./pricing.commit')
        ],
        status: [
            async.apply(require('./status.readyprocess'), conf),
            require('./getcurrencyexchanges'),
            require('./getcountries'),
            require('./getproduct'),
            require('./getaffiliate'),
            require('./getdmc'),
            require('./getbooking'),
            require('./getquery'),
            require('./getquote'),
            require('./status.change'),
            require('./book.addstory'),
            require('./book.savebooking'),
            require('./savequery'),
            require('./savequote'),
            require('./hermes'),
            require('./status.recoverandexit')
        ],
        quotation: [
            async.apply(require('./quotation.datavalidation'), conf),
            require('./quotation.readyprocess'),
            require('./getcurrencyexchanges'),
            require('./getaffiliate'),
            require('./getdmc'),
            require('./quotation.price'),
            require('./quotation.commit'),
        ],
        adminstatistics: [
            async.apply(require('./admin.readyprocess'), conf),
            require('./admin.getbookings'),
            require('./admin.getprograms'),
            require('./admin.getaffiliates'),
            require('./admin.getdmcs'),
            require('./admin.gettaylormade'),
            require('./admin.commit')
        ]
    };
}