<h2>
    The Program Confirmed 
</h2>
<!-- END CONTROL OMT -->
<div programpreview ng-if="tabs[3].active"
        program="booking.products[0]"
        quote="booking.quote"
        booking="booking"
        language="EN"
        openedit="booking.products[0] == null"
        removeeditor="loginsession.user.isAdmin == null || loginsession.user.isAdmin == false"
        removebuttons="false" ng-cloak ></div>
