var schemafields = module.exports.schemafields = {
    WLCustomizations: [
        "_id",
        "code",
        "name",
        "slug",
        "css.brand_background",
        "css.brand_primary",
        "css.brand_alternate",
        "css.brand_info",
        "css.brand_warning",
        "css.brand_danger",
        "web.header",
        "web.footer",
        "createdOn",
        "updatedOn",
        "__v"
    ],
    Affiliate: [
        "_id",
        "code",
        "name",
        "slug",
        "company.legalname",
        "company.name",
        "company.constitutionyear",
        "company.taxid",
        "company.phone",
        "company.celphone",
        "company.agencylic",
        "company.emergencyphone",
        "company.website",
        "company.group",
        "company.location.fulladdress",
        "company.location.city",
        "company.location.stateorprovince",
        "company.location.cp",
        "company.location.country",
        "company.location.countrycode",
        "company.location.continent",
        "company.location.latitude",
        "company.location.longitude",
        "company.location.route",
        "contact.firstname",
        "contact.lastname",
        "contact.email",
        "contact.fax",
        "contact.skype",
        "contact.position",
        "contact.marketingContact.name",
        "contact.marketingContact.email",
        "contact.bookingContact.email",
        "contact.paymentContact.firstname",
        "contact.paymentContact.lastname",
        "contact.paymentContact.phone",
        "contact.paymentContact.email",
        "contact.paymentContact.location.fulladdress",
        "contact.paymentContact.location.city",
        "contact.paymentContact.location.stateorprovince",
        "contact.paymentContact.location.cp",
        "contact.paymentContact.location.country",
        "contact.paymentContact.location.countrycode",
        "contact.paymentContact.location.continent",
        "contact.paymentContact.location.latitude",
        "contact.paymentContact.location.longitude",
        "contact.paymentContact.location.route",
        "bankinfo.beneficiary",
        "bankinfo.iban",
        "bankinfo.accountingnumber",
        "bankinfo.accountnumber",
        "bankinfo.bankname",
        "bankinfo.bic",
        "bankinfo.routing",
        "bankinfo.bankaddress",
        "bankinfo.bankzip",
        "bankinfo.bankcity",
        "bankinfo.bankcountry.label",
        "bankinfo.bankcountry.value",
        "membership.omtmargin",
        "membership.acceptterms",
        "membership.membershipDate",
        "membership.validateDate",
        "membership.registervalid",
        "membership.requestdelete",
        "membership.colaborationagree",
        "membership.wlcollaborationagree",
        "images.photo.public_id",
        "images.photo.version",
        "images.photo.signature",
        "images.photo.format",
        "images.photo.resource_type",
        "images.photo.url",
        "images.photo.width",
        "images.photo.height",
        "images.photo.secure_url",
        "images.logo.public_id",
        "images.logo.version",
        "images.logo.signature",
        "images.logo.format",
        "images.logo.resource_type",
        "images.logo.url",
        "images.logo.width",
        "images.logo.height",
        "images.logo.secure_url",
        "images.splash.public_id",
        "images.splash.version",
        "images.splash.signature",
        "images.splash.format",
        "images.splash.resource_type",
        "images.splash.url",
        "images.splash.width",
        "images.splash.height",
        "images.splash.secure_url",
        "currency.label",
        "currency.symbol",
        "currency.value",
        "timeZone.gmtAdjustment",
        "timeZone.label",
        "timeZone.timeZoneId",
        "timeZone.useDaylightTime",
        "timeZone.value",
        "omtcomment",
        "fees.unique",
        "fees.groups",
        "fees.tailormade",
        "fees.flights",
        "companynameindexing",
        "contactnameindexing",
        "companylocationindexing",
        "user",
        "wlcustom",
        "createdOn",
        "updatedOn",
        "__v"
    ],
    SigninRegister: [
        "_id",
        "code",
        "username",
        "name",
        "lastname",
        "email",
        "phone",
        "kind",
        "createdOn",
        "updatedOn",
        "__v"
    ],
    Bookings: [
        "_id",
        "idBooking",
        "slug",
        "idBookingExt",
        "comission",
        "iva",
        "start.year",
        "start.month",
        "start.monthname_es",
        "start.monthname_en",
        "start.day",
        "startdate",
        "startdateindexing",
        "end.year",
        "end.month",
        "end.monthname_es",
        "end.monthname_en",
        "end.day",
        "enddate",
        "enddateindexing",
        "createdonindexing",
        "holderindexing",
        "destinationindexing",
        "destinationindexinges",
        "productDmc",
        "product",
        "dmc",
        "dmcindexing",
        "traveler",
        "affiliate",
        "affiliateindexing",
        "flights",
        "createDate",
        "cancelDate",
        "lastModifiedDate",
        "isGroup",
        "isB2C",
        "b2bcommission",
        "omtmargin",
        "fees.unique",
        "fees.groups",
        "fees.tailormade",
        "fees.flights",
        "invoice",
        "invoiceDate",
        "invoiceProvider",
        "invoiceProviderDate",
        "invoiceProviderFile",
        "invoiceAffiliate",
        "invoiceAffiliateDate",
        "invoiceAffiliateFile",
        "finalDatePaymentAffiliate",
        "voucherFile",
        "status",
        "meetingdata",
        "queryCode",
        "quoteCode",
        "budgetCode",
        "budget",
        "timeZone.label",
        "timeZone.useDaylightTime",
        "timeZone.value",
        "discount.label",
        "discount.value",
        "discount.code",
        "lastVisitUser",
        "lastVisitDMC",
        "lastVisitOMT",
        "historic",
        "observations",
        "affiliateobservations",
        "affiliateuser",
        "cancelpolicy._es",
        "cancelpolicy._en",
        "comments",
        "pvpAffiliate.value",
        "pvpAffiliate.currency.label",
        "pvpAffiliate.currency.symbol",
        "pvpAffiliate.currency.value",
        "pvpAffiliate.exchange.value",
        "pvpAffiliate.exchange.currency.label",
        "pvpAffiliate.exchange.currency.symbol",
        "pvpAffiliate.exchange.currency.value",
        "amount.value",
        "amount.currency.label",
        "amount.currency.symbol",
        "amount.currency.value",
        "amount.exchange.value",
        "amount.exchange.currency.label",
        "amount.exchange.currency.symbol",
        "amount.exchange.currency.value",
        "amountflights.value",
        "amountflights.currency.label",
        "amountflights.currency.symbol",
        "amountflights.currency.value",
        "amountflights.exchange.value",
        "amountflights.exchange.currency.label",
        "amountflights.exchange.currency.symbol",
        "amountflights.exchange.currency.value",
        "netPrice.value",
        "netPrice.currency.label",
        "netPrice.currency.symbol",
        "netPrice.currency.value",
        "netPrice.exchange.value",
        "netPrice.exchange.currency.label",
        "netPrice.exchange.currency.symbol",
        "netPrice.exchange.currency.value",
        "userinvoicedata.wantinvoice",
        "userinvoicedata.invoicevalidate",
        "userinvoicedata.name",
        "userinvoicedata.city",
        "userinvoicedata.cp",
        "userinvoicedata.idnumber",
        "userinvoicedata.invoicenumber",
        "userinvoicedata.taxinvoice",
        "userinvoicedata.address",
        "userinvoicedata.invoicedate",
        "userinvoicedata.country.name_es",
        "userinvoicedata.country.name",
        "userinvoicedata.country.countrycode",
        "userinvoicedata.invoiceFile",
        "roomDistribution",
        "payStatus",
        "payProvider",
        "accountingEntries",
        "createdOn",
        "updatedOn",
        "__v"
    ],
    Bookings2: [
        "_id",
        "idBooking",
        "slug",
        "idBookingExt",
        "code",
        "agentid",
        "agencyid",
        "bookingmodel",
        "paymentmodel",
        "dates.start.year",
        "dates.start.month",
        "dates.start.monthname_es",
        "dates.start.monthname_en",
        "dates.start.day",
        "dates.end.year",
        "dates.end.month",
        "dates.end.monthname_es",
        "dates.end.monthname_en",
        "dates.end.day",
        "dates.canceldate.year",
        "dates.canceldate.month",
        "dates.canceldate.monthname_es",
        "dates.canceldate.monthname_en",
        "dates.canceldate.day",
        "dates.finalpayment.year",
        "dates.finalpayment.month",
        "dates.finalpayment.monthname_es",
        "dates.finalpayment.monthname_en",
        "dates.finalpayment.day",
        "dates.lastvisituser",
        "dates.lastvisitdmc",
        "dates.lastvisitomt",
        "dates.lastvisitaffiliate",
        "meetingdata",
        "previousstatus",
        "status",
        "chargestatus",
        "paystatusprovider",
        "paystatusagency",
        "startdateindexing",
        "enddateindexing",
        "createdonindexing",
        "affiliateindexing",
        "dmcindexing",
        "destinationindexing",
        "paxindexing",
        "textindexing",
        "products",
        "dmc",
        "traveler",
        "affiliate",
        "query",
        "quote",
        "payments",
        "stories",
        "signin",
        "flights",
        "invoices",
        "relatedbooking",
        "pricing.comission",
        "pricing.iva",
        "pricing.amount",
        "pricing.currency.label",
        "pricing.currency.symbol",
        "pricing.currency.value",
        "pricing.fee",
        "pricing.margin",
        "pricing.minpaxoperate",
        "pricing.rooms.double",
        "pricing.rooms.single",
        "pricing.rooms.triple",
        "pricing.roomssnapshot.double",
        "pricing.roomssnapshot.single",
        "pricing.roomssnapshot.triple",
        "voucher.file",
        "timezone.label",
        "timezone.useDaylightTime",
        "timezone.value",
        "observations.label_es",
        "observations.label_en",
        "observations.observations",
        "observations.signing",
        "cancelpolicy._en",
        "cancelpolicy._es",
        "exchanges",
        "mailing",
        "paxes",
        "rooms",
        "createdOn",
        "updatedOn",
        "__v"
    ],
    Chats: [
        "_id",
        "code",
        "title",
        "slug",
        "date",
        "userquery",
        "booking",
        "quote",
        "traveler",
        "dmc",
        "affiliate",
        "status",
        "messages",
        "createdOn",
        "updatedOn",
        "__v"
    ],
    DestinationCountriesZones: [
        "_id",
        "label_es",
        "label_en",
        "slug",
        "promotionArea",
        "promotionOrder",
        "title_es",
        "title_en",
        "mainImage.public_id",
        "mainImage.version",
        "mainImage.signature",
        "mainImage.format",
        "mainImage.resource_type",
        "mainImage.url",
        "mainImage.width",
        "mainImage.height",
        "mainImage.secure_url",
        "captionImage",
        "iconImage.public_id",
        "iconImage.version",
        "iconImage.signature",
        "iconImage.format",
        "iconImage.resource_type",
        "iconImage.url",
        "iconImage.width",
        "iconImage.height",
        "iconImage.secure_url",
        "colorBg",
        "sortOrder",
        "key",
        "__v"
    ],
    DestinationCountries: [
        "_id",
        "label_es",
        "label_en",
        "slug",
        "key_es",
        "key_en",
        "location.country",
        "location.name",
        "location.number",
        "location.postcode",
        "location.state",
        "location.street1",
        "location.street2",
        "location.suburb",
        "location.latitude",
        "location.longitude",
        "zone",
        "title_es",
        "title_en",
        "mainImage.public_id",
        "mainImage.version",
        "mainImage.signature",
        "mainImage.format",
        "mainImage.resource_type",
        "mainImage.url",
        "mainImage.width",
        "mainImage.height",
        "mainImage.secure_url",
        "captionImage",
        "description_es",
        "description_en",
        "averageEuro",
        "state",
        "publishedDate",
        "titleSEO_es",
        "metaDescription_es",
        "descriptionGooglePlus_es",
        "descriptionFacebook_es",
        "titleSEO_en",
        "metaDescription_en",
        "descriptionGooglePlus_en",
        "descriptionFacebook_en",
        "imageFacebook.public_id",
        "imageFacebook.version",
        "imageFacebook.signature",
        "imageFacebook.format",
        "imageFacebook.resource_type",
        "imageFacebook.url",
        "imageFacebook.width",
        "imageFacebook.height",
        "imageFacebook.secure_url",
        "__v"
    ],
    DestinationCities: [
        "_id",
        "label_es",
        "label_en",
        "slug",
        "key_es",
        "key_en",
        "location.country",
        "location.name",
        "location.number",
        "location.postcode",
        "location.state",
        "location.street1",
        "location.street2",
        "location.suburb",
        "location.latitude",
        "location.longitude",
        "country",
        "countrycode",
        "title_es",
        "title_en",
        "mainImage.public_id",
        "mainImage.version",
        "mainImage.signature",
        "mainImage.format",
        "mainImage.resource_type",
        "mainImage.url",
        "mainImage.width",
        "mainImage.height",
        "mainImage.secure_url",
        "captionImage",
        "description_es",
        "description_en",
        "state",
        "publishedDate",
        "titleSEO_es",
        "metaDescription_es",
        "descriptionGooglePlus_es",
        "descriptionFacebook_es",
        "titleSEO_en",
        "metaDescription_en",
        "descriptionGooglePlus_en",
        "descriptionFacebook_en",
        "imageFacebook.public_id",
        "imageFacebook.version",
        "imageFacebook.signature",
        "imageFacebook.format",
        "imageFacebook.resource_type",
        "imageFacebook.url",
        "imageFacebook.width",
        "imageFacebook.height",
        "imageFacebook.secure_url",
        "__v"
    ],
    DMCProducts: [
        "_id",
        "name",
        "title",
        "title_es",
        "languages.english",
        "languages.spanish",
        "slug",
        "slug_en",
        "slug_es",
        "publishedDate",
        "publishState",
        "code",
        "dmccode",
        "description_en",
        "description_es",
        "important_txt_en",
        "important_txt_es",
        "parent",
        "release",
        "availabilitytill",
        "productimage.public_id",
        "productimage.version",
        "productimage.signature",
        "productimage.format",
        "productimage.resource_type",
        "productimage.url",
        "productimage.width",
        "productimage.height",
        "productimage.secure_url",
        "location.fulladdress",
        "location.city",
        "location.city_es",
        "location.citybehaviour",
        "location.stateorprovince",
        "location.cp",
        "location.country",
        "location.countrycode",
        "location.continent",
        "location.latitude",
        "location.longitude",
        "included.trip.grouptrip",
        "included.trip.privatetrip",
        "included.trip.minpaxoperate",
        "included.arrivaltransfer",
        "included.arrivalassistance",
        "included.arrivallanguage.spanish",
        "included.arrivallanguage.english",
        "included.arrivallanguage.french",
        "included.arrivallanguage.german",
        "included.arrivallanguage.italian",
        "included.arrivallanguage.portuguese",
        "included.departuretransfer",
        "included.departureassistance",
        "included.departurelanguage.spanish",
        "included.departurelanguage.english",
        "included.departurelanguage.french",
        "included.departurelanguage.german",
        "included.departurelanguage.italian",
        "included.departurelanguage.portuguese",
        "included.tourescort.included",
        "included.tourescort.language.spanish",
        "included.tourescort.language.english",
        "included.tourescort.language.french",
        "included.tourescort.language.german",
        "included.tourescort.language.italian",
        "included.tourescort.language.portuguese",
        "included.driveguide.included",
        "included.driveguide.language.spanish",
        "included.driveguide.language.english",
        "included.driveguide.language.french",
        "included.driveguide.language.german",
        "included.driveguide.language.italian",
        "included.driveguide.language.portuguese",
        "included.transportbetweencities.included",
        "included.transportbetweencities.bus",
        "included.transportbetweencities.domesticflight",
        "included.transportbetweencities.train",
        "included.transportbetweencities.boat",
        "included.transportbetweencities.privatecarwithdriver",
        "included.transportbetweencities.privatecarwithdriverandguide",
        "included.transportbetweencities.fourxfour",
        "included.transportbetweencities.van",
        "included.transportbetweencities.truck",
        "included.transportbetweencities.other",
        "included.transportbetweencities.otherdescription",
        "included.taxesinthecountry",
        "included.airporttaxes",
        "included.tips",
        "included.baggagehandlingfees",
        "pvp.keep",
        "pvp.b2c",
        "pvp.b2b",
        "pvp.b2cperday",
        "pvp.b2bperday",
        "pvp.currency.label",
        "pvp.currency.symbol",
        "pvp.currency.value",
        "pvp.year",
        "pvp.month",
        "pvp.day",
        "channels",
        "priceindexing",
        "priceb2bindexing",
        "itinerarylength",
        "itinerarylengthindexing",
        "dmcindexing",
        "destinationindexing",
        "productvalid",
        "dmc",
        "origin",
        "departurecity",
        "stopcities",
        "sleepcity",
        "departurecountry",
        "stopcountry",
        "sleepcountry",
        "flightsdmc",
        "flights",
        "categoryname.label_es",
        "categoryname.label_en",
        "minprice.value",
        "minprice.b2b",
        "minprice.currency.label",
        "minprice.currency.symbol",
        "minprice.currency.value",
        "minprice.year",
        "minprice.month",
        "minprice.day",
        "minprice.exchange.value",
        "minprice.exchange.b2b",
        "minprice.exchange.currency.label",
        "minprice.exchange.currency.symbol",
        "minprice.exchange.currency.value",
        "prices",
        "itinerary",
        "availability",
        "tags",
        "createdOn",
        "updatedOn",
        "__v"
    ],
    BookedProducts: [
        "_id",
        "name",
        "title",
        "title_es",
        "languages.english",
        "languages.spanish",
        "slug",
        "slug_en",
        "slug_es",
        "publishedDate",
        "publishState",
        "code",
        "dmccode",
        "description_en",
        "description_es",
        "important_txt_en",
        "important_txt_es",
        "parent",
        "release",
        "productimage.public_id",
        "productimage.version",
        "productimage.signature",
        "productimage.format",
        "productimage.resource_type",
        "productimage.url",
        "productimage.width",
        "productimage.height",
        "productimage.secure_url",
        "location.fulladdress",
        "location.city",
        "location.city_es",
        "location.citybehaviour",
        "location.stateorprovince",
        "location.cp",
        "location.country",
        "location.countrycode",
        "location.continent",
        "location.latitude",
        "location.longitude",
        "included.trip.grouptrip",
        "included.trip.privatetrip",
        "included.trip.minpaxoperate",
        "included.arrivaltransfer",
        "included.arrivalassistance",
        "included.arrivallanguage.spanish",
        "included.arrivallanguage.english",
        "included.arrivallanguage.french",
        "included.arrivallanguage.german",
        "included.arrivallanguage.italian",
        "included.arrivallanguage.portuguese",
        "included.departuretransfer",
        "included.departureassistance",
        "included.departurelanguage.spanish",
        "included.departurelanguage.english",
        "included.departurelanguage.french",
        "included.departurelanguage.german",
        "included.departurelanguage.italian",
        "included.departurelanguage.portuguese",
        "included.tourescort.included",
        "included.tourescort.language.spanish",
        "included.tourescort.language.english",
        "included.tourescort.language.french",
        "included.tourescort.language.german",
        "included.tourescort.language.italian",
        "included.tourescort.language.portuguese",
        "included.driveguide.included",
        "included.driveguide.language.spanish",
        "included.driveguide.language.english",
        "included.driveguide.language.french",
        "included.driveguide.language.german",
        "included.driveguide.language.italian",
        "included.driveguide.language.portuguese",
        "included.transportbetweencities.included",
        "included.transportbetweencities.bus",
        "included.transportbetweencities.domesticflight",
        "included.transportbetweencities.train",
        "included.transportbetweencities.boat",
        "included.transportbetweencities.privatecarwithdriver",
        "included.transportbetweencities.privatecarwithdriverandguide",
        "included.transportbetweencities.fourxfour",
        "included.transportbetweencities.van",
        "included.transportbetweencities.truck",
        "included.transportbetweencities.other",
        "included.transportbetweencities.otherdescription",
        "included.taxesinthecountry",
        "included.airporttaxes",
        "included.tips",
        "included.baggagehandlingfees",
        "pvp.keep",
        "pvp.b2c",
        "pvp.b2b",
        "pvp.currency.label",
        "pvp.currency.symbol",
        "pvp.currency.value",
        "pvp.year",
        "pvp.month",
        "pvp.day",
        "priceindexing",
        "priceb2bindexing",
        "itinerarylength",
        "itinerarylengthindexing",
        "productvalid",
        "dmc",
        "origin",
        "departurecity",
        "stopcities",
        "sleepcity",
        "departurecountry",
        "stopcountry",
        "sleepcountry",
        "flightsdmc",
        "flights",
        "categoryname.label_es",
        "categoryname.label_en",
        "minprice.value",
        "minprice.b2b",
        "minprice.currency.label",
        "minprice.currency.symbol",
        "minprice.currency.value",
        "minprice.year",
        "minprice.month",
        "minprice.day",
        "minprice.exchange.value",
        "minprice.exchange.b2b",
        "minprice.exchange.currency.label",
        "minprice.exchange.currency.symbol",
        "minprice.exchange.currency.value",
        "prices",
        "itinerary",
        "availability",
        "tags",
        "createdOn",
        "updatedOn",
        "__v"
    ],
    RemovedDMCProducts: [
        "_id",
        "name",
        "title",
        "title_es",
        "languages.english",
        "languages.spanish",
        "slug",
        "slug_en",
        "slug_es",
        "publishedDate",
        "publishState",
        "code",
        "dmccode",
        "description_en",
        "description_es",
        "important_txt_en",
        "important_txt_es",
        "parent",
        "release",
        "productimage.public_id",
        "productimage.version",
        "productimage.signature",
        "productimage.format",
        "productimage.resource_type",
        "productimage.url",
        "productimage.width",
        "productimage.height",
        "productimage.secure_url",
        "location.fulladdress",
        "location.city",
        "location.city_es",
        "location.citybehaviour",
        "location.stateorprovince",
        "location.cp",
        "location.country",
        "location.countrycode",
        "location.continent",
        "location.latitude",
        "location.longitude",
        "included.trip.grouptrip",
        "included.trip.privatetrip",
        "included.trip.minpaxoperate",
        "included.arrivaltransfer",
        "included.arrivalassistance",
        "included.arrivallanguage.spanish",
        "included.arrivallanguage.english",
        "included.arrivallanguage.french",
        "included.arrivallanguage.german",
        "included.arrivallanguage.italian",
        "included.arrivallanguage.portuguese",
        "included.departuretransfer",
        "included.departureassistance",
        "included.departurelanguage.spanish",
        "included.departurelanguage.english",
        "included.departurelanguage.french",
        "included.departurelanguage.german",
        "included.departurelanguage.italian",
        "included.departurelanguage.portuguese",
        "included.tourescort.included",
        "included.tourescort.language.spanish",
        "included.tourescort.language.english",
        "included.tourescort.language.french",
        "included.tourescort.language.german",
        "included.tourescort.language.italian",
        "included.tourescort.language.portuguese",
        "included.driveguide.included",
        "included.driveguide.language.spanish",
        "included.driveguide.language.english",
        "included.driveguide.language.french",
        "included.driveguide.language.german",
        "included.driveguide.language.italian",
        "included.driveguide.language.portuguese",
        "included.transportbetweencities.included",
        "included.transportbetweencities.bus",
        "included.transportbetweencities.domesticflight",
        "included.transportbetweencities.train",
        "included.transportbetweencities.boat",
        "included.transportbetweencities.privatecarwithdriver",
        "included.transportbetweencities.privatecarwithdriverandguide",
        "included.transportbetweencities.fourxfour",
        "included.transportbetweencities.van",
        "included.transportbetweencities.truck",
        "included.transportbetweencities.other",
        "included.transportbetweencities.otherdescription",
        "included.taxesinthecountry",
        "included.airporttaxes",
        "included.tips",
        "included.baggagehandlingfees",
        "priceindexing",
        "itinerarylength",
        "itinerarylengthindexing",
        "productvalid",
        "dmc",
        "origin",
        "categoryname.label_es",
        "categoryname.label_en",
        "minprice.value",
        "minprice.currency.label",
        "minprice.currency.symbol",
        "minprice.currency.value",
        "minprice.year",
        "minprice.month",
        "minprice.exchange.value",
        "minprice.exchange.currency.label",
        "minprice.exchange.currency.symbol",
        "minprice.exchange.currency.value",
        "prices",
        "itinerary",
        "availability",
        "tags",
        "createdOn",
        "updatedOn",
        "__v"
    ],
    DMCs: [
        "_id",
        "code",
        "name",
        "vouchername",
        "slug",
        "contact.title",
        "contact.name.first",
        "contact.name.last",
        "contact.firstname",
        "contact.lastname",
        "contact.email",
        "contact.fax",
        "contact.skype",
        "contact.nif",
        "contact.position",
        "contact.accountingContact.name",
        "contact.accountingContact.email",
        "contact.bookingContact.email",
        "contact.prodContact.email",
        "contact.reqFITContact.email",
        "contact.reqGroupContact.email",
        "bankinfo.beneficiary",
        "bankinfo.iban",
        "bankinfo.accountingnumber",
        "bankinfo.accountnumber",
        "bankinfo.bankname",
        "bankinfo.bic",
        "bankinfo.routing",
        "bankinfo.bankaddress",
        "bankinfo.bankzip",
        "bankinfo.bankcity",
        "bankinfo.bankcountry.label",
        "bankinfo.bankcountry.value",
        "membershipDate",
        "membership.b2bchannel",
        "membership.b2cchannel",
        "membership.commission",
        "membership.b2bcommission",
        "membership.acceptterms",
        "membership.membershipDate",
        "membership.registervalid",
        "membership.publicprofilecomplete",
        "membership.companyimagescomplete",
        "membership.companycomplete",
        "membership.paymentcomplete",
        "membership.averagecomplete",
        "membership.companytaxid",
        "membership.emergencycomplete",
        "membership.requestdelete",
        "membership.toursmultidays",
        "membership.tailormade",
        "membership.groups",
        "membership.payagreement",
        "membership.autopublish",
        "membership.confirmterms",
        "membership.paymentoption.slug",
        "membership.paymentoption._en",
        "membership.paymentoption._es",
        "membership.cancelpolicy._es",
        "membership.cancelpolicy._en",
        "membership.pvp.keep",
        "images.photo.public_id",
        "images.photo.version",
        "images.photo.signature",
        "images.photo.format",
        "images.photo.resource_type",
        "images.photo.url",
        "images.photo.width",
        "images.photo.height",
        "images.photo.secure_url",
        "images.logo.public_id",
        "images.logo.version",
        "images.logo.signature",
        "images.logo.format",
        "images.logo.resource_type",
        "images.logo.url",
        "images.logo.width",
        "images.logo.height",
        "images.logo.secure_url",
        "images.splash.public_id",
        "images.splash.version",
        "images.splash.signature",
        "images.splash.format",
        "images.splash.resource_type",
        "images.splash.url",
        "images.splash.width",
        "images.splash.height",
        "images.splash.secure_url",
        "currency.label",
        "currency.symbol",
        "currency.value",
        "timeZone.gmtAdjustment",
        "timeZone.label",
        "timeZone.timeZoneId",
        "timeZone.useDaylightTime",
        "timeZone.value",
        "omtcomment",
        "user",
        "admin",
        "contactuser",
        "delegations",
        "company.legalname",
        "company.name",
        "company.constitutionyear",
        "company.taxid",
        "company.phone",
        "company.emergencyphone",
        "company.website",
        "company.operatein",
        "company.location.fulladdress",
        "company.location.city",
        "company.location.stateorprovince",
        "company.location.cp",
        "company.location.country",
        "company.location.countrycode",
        "company.location.continent",
        "company.location.latitude",
        "company.location.longitude",
        "additionalinfo.description",
        "additionalinfo.description_es",
        "additionalinfo.recomenders",
        "additionalinfo.tripadvisorurl",
        "additionalinfo.associations",
        "additionalinfo.registration.url",
        "additionalinfo.insurancepolicy.url",
        "additionalinfo.businessLicencense",
        "additionalinfo.notpunished",
        "additionalinfo.paymenttaxes",
        "tourEscorts",
        "tags",
        "expenditure",
        "createdOn",
        "updatedOn",
        "__v"
    ],
    Mails: [
        "_id",
        "title",
        "slug",
        "from",
        "to",
        "subject",
        "text",
        "html",
        "date",
        "type",
        "tags",
        "createdOn",
        "updatedOn",
        "__v"
    ],
    MigrationProducts: [
        "_id",
        "name",
        "title",
        "title_es",
        "languages.english",
        "languages.spanish",
        "slug",
        "slug_en",
        "slug_es",
        "publishedDate",
        "publishState",
        "code",
        "dmccode",
        "description_en",
        "description_es",
        "important_txt_en",
        "important_txt_es",
        "parent",
        "release",
        "productimage.public_id",
        "productimage.version",
        "productimage.signature",
        "productimage.format",
        "productimage.resource_type",
        "productimage.url",
        "productimage.width",
        "productimage.height",
        "productimage.secure_url",
        "location.fulladdress",
        "location.city",
        "location.city_es",
        "location.citybehaviour",
        "location.stateorprovince",
        "location.cp",
        "location.country",
        "location.countrycode",
        "location.continent",
        "location.latitude",
        "location.longitude",
        "included.trip.grouptrip",
        "included.trip.privatetrip",
        "included.trip.minpaxoperate",
        "included.arrivaltransfer",
        "included.arrivalassistance",
        "included.arrivallanguage.spanish",
        "included.arrivallanguage.english",
        "included.arrivallanguage.french",
        "included.arrivallanguage.german",
        "included.arrivallanguage.italian",
        "included.arrivallanguage.portuguese",
        "included.departuretransfer",
        "included.departureassistance",
        "included.departurelanguage.spanish",
        "included.departurelanguage.english",
        "included.departurelanguage.french",
        "included.departurelanguage.german",
        "included.departurelanguage.italian",
        "included.departurelanguage.portuguese",
        "included.tourescort.included",
        "included.tourescort.language.spanish",
        "included.tourescort.language.english",
        "included.tourescort.language.french",
        "included.tourescort.language.german",
        "included.tourescort.language.italian",
        "included.tourescort.language.portuguese",
        "included.driveguide.included",
        "included.driveguide.language.spanish",
        "included.driveguide.language.english",
        "included.driveguide.language.french",
        "included.driveguide.language.german",
        "included.driveguide.language.italian",
        "included.driveguide.language.portuguese",
        "included.transportbetweencities.included",
        "included.transportbetweencities.bus",
        "included.transportbetweencities.domesticflight",
        "included.transportbetweencities.train",
        "included.transportbetweencities.boat",
        "included.transportbetweencities.privatecarwithdriver",
        "included.transportbetweencities.privatecarwithdriverandguide",
        "included.transportbetweencities.fourxfour",
        "included.transportbetweencities.van",
        "included.transportbetweencities.truck",
        "included.transportbetweencities.other",
        "included.transportbetweencities.otherdescription",
        "included.taxesinthecountry",
        "included.airporttaxes",
        "included.tips",
        "included.baggagehandlingfees",
        "priceindexing",
        "itinerarylength",
        "itinerarylengthindexing",
        "productvalid",
        "dmc",
        "origin",
        "departurecity",
        "stopcities",
        "sleepcity",
        "departurecountry",
        "stopcountry",
        "sleepcountry",
        "categoryname.label_es",
        "categoryname.label_en",
        "minprice.value",
        "minprice.currency.label",
        "minprice.currency.symbol",
        "minprice.currency.value",
        "minprice.year",
        "minprice.month",
        "minprice.exchange.value",
        "minprice.exchange.currency.label",
        "minprice.exchange.currency.symbol",
        "minprice.exchange.currency.value",
        "prices",
        "itinerary",
        "availability",
        "tags",
        "createdOn",
        "updatedOn",
        "__v"
    ],
    OMTAdminRequests: [
        "_id",
        "title",
        "slug",
        "from",
        "to",
        "subject",
        "text",
        "html",
        "date",
        "type",
        "key",
        "tags",
        "createdOn",
        "updatedOn",
        "__v"
    ],
    Permissions: [
        "_id",
        "title",
        "slug",
        "publishedDate",
        "description",
        "createdOn",
        "updatedOn",
        "__v"
    ],
    Quotes: [
        "_id",
        "title_en",
        "title_es",
        "code",
        "slug",
        "publishedDate",
        "description",
        "name",
        "createdonindexing",
        "responseDetails.comments",
        "responseDetails.conditions",
        "responseDetails.cancelpolicy._es",
        "responseDetails.cancelpolicy._en",
        "products",
        "userqueryCode",
        "userqueryId",
        "idBooking",
        "travelercode",
        "affiliatecode",
        "dmccode",
        "operationStart.year",
        "operationStart.month",
        "operationStart.monthname_es",
        "operationStart.monthname_en",
        "operationStart.day",
        "operationStartDate",
        "quoteValidUntil.year",
        "quoteValidUntil.month",
        "quoteValidUntil.monthname_es",
        "quoteValidUntil.monthname_en",
        "quoteValidUntil.day",
        "quoteValidDate",
        "chat",
        "status",
        "comission",
        "isB2C",
        "b2bcommission",
        "omtmargin",
        "fees.unique",
        "fees.groups",
        "fees.tailormade",
        "fees.flights",
        "rooms.single.quantity",
        "rooms.single.pricePerPax.value",
        "rooms.single.pricePerPax.currency.label",
        "rooms.single.pricePerPax.currency.symbol",
        "rooms.single.pricePerPax.currency.value",
        "rooms.single.pricePerPax.exchange.value",
        "rooms.single.pricePerPax.exchange.currency.label",
        "rooms.single.pricePerPax.exchange.currency.symbol",
        "rooms.single.pricePerPax.exchange.currency.value",
        "rooms.single.amountPricePerPax.value",
        "rooms.single.amountPricePerPax.currency.label",
        "rooms.single.amountPricePerPax.currency.symbol",
        "rooms.single.amountPricePerPax.currency.value",
        "rooms.single.amountPricePerPax.exchange.value",
        "rooms.single.amountPricePerPax.exchange.currency.label",
        "rooms.single.amountPricePerPax.exchange.currency.symbol",
        "rooms.single.amountPricePerPax.exchange.currency.value",
        "rooms.single.pvpAffiliatePerPax.value",
        "rooms.single.pvpAffiliatePerPax.currency.label",
        "rooms.single.pvpAffiliatePerPax.currency.symbol",
        "rooms.single.pvpAffiliatePerPax.currency.value",
        "rooms.single.pvpAffiliatePerPax.exchange.value",
        "rooms.single.pvpAffiliatePerPax.exchange.currency.label",
        "rooms.single.pvpAffiliatePerPax.exchange.currency.symbol",
        "rooms.single.pvpAffiliatePerPax.exchange.currency.value",
        "rooms.double.quantity",
        "rooms.double.pricePerPax.value",
        "rooms.double.pricePerPax.currency.label",
        "rooms.double.pricePerPax.currency.symbol",
        "rooms.double.pricePerPax.currency.value",
        "rooms.double.pricePerPax.exchange.value",
        "rooms.double.pricePerPax.exchange.currency.label",
        "rooms.double.pricePerPax.exchange.currency.symbol",
        "rooms.double.pricePerPax.exchange.currency.value",
        "rooms.double.amountPricePerPax.value",
        "rooms.double.amountPricePerPax.currency.label",
        "rooms.double.amountPricePerPax.currency.symbol",
        "rooms.double.amountPricePerPax.currency.value",
        "rooms.double.amountPricePerPax.exchange.value",
        "rooms.double.amountPricePerPax.exchange.currency.label",
        "rooms.double.amountPricePerPax.exchange.currency.symbol",
        "rooms.double.amountPricePerPax.exchange.currency.value",
        "rooms.double.pvpAffiliatePerPax.value",
        "rooms.double.pvpAffiliatePerPax.currency.label",
        "rooms.double.pvpAffiliatePerPax.currency.symbol",
        "rooms.double.pvpAffiliatePerPax.currency.value",
        "rooms.double.pvpAffiliatePerPax.exchange.value",
        "rooms.double.pvpAffiliatePerPax.exchange.currency.label",
        "rooms.double.pvpAffiliatePerPax.exchange.currency.symbol",
        "rooms.double.pvpAffiliatePerPax.exchange.currency.value",
        "rooms.triple.quantity",
        "rooms.triple.pricePerPax.value",
        "rooms.triple.pricePerPax.currency.label",
        "rooms.triple.pricePerPax.currency.symbol",
        "rooms.triple.pricePerPax.currency.value",
        "rooms.triple.pricePerPax.exchange.value",
        "rooms.triple.pricePerPax.exchange.currency.label",
        "rooms.triple.pricePerPax.exchange.currency.symbol",
        "rooms.triple.pricePerPax.exchange.currency.value",
        "rooms.triple.amountPricePerPax.value",
        "rooms.triple.amountPricePerPax.currency.label",
        "rooms.triple.amountPricePerPax.currency.symbol",
        "rooms.triple.amountPricePerPax.currency.value",
        "rooms.triple.amountPricePerPax.exchange.value",
        "rooms.triple.amountPricePerPax.exchange.currency.label",
        "rooms.triple.amountPricePerPax.exchange.currency.symbol",
        "rooms.triple.amountPricePerPax.exchange.currency.value",
        "rooms.triple.pvpAffiliatePerPax.value",
        "rooms.triple.pvpAffiliatePerPax.currency.label",
        "rooms.triple.pvpAffiliatePerPax.currency.symbol",
        "rooms.triple.pvpAffiliatePerPax.currency.value",
        "rooms.triple.pvpAffiliatePerPax.exchange.value",
        "rooms.triple.pvpAffiliatePerPax.exchange.currency.label",
        "rooms.triple.pvpAffiliatePerPax.exchange.currency.symbol",
        "rooms.triple.pvpAffiliatePerPax.exchange.currency.value",
        "rooms.quad.quantity",
        "rooms.quad.pricePerPax.value",
        "rooms.quad.pricePerPax.currency.label",
        "rooms.quad.pricePerPax.currency.symbol",
        "rooms.quad.pricePerPax.currency.value",
        "rooms.quad.pricePerPax.exchange.value",
        "rooms.quad.pricePerPax.exchange.currency.label",
        "rooms.quad.pricePerPax.exchange.currency.symbol",
        "rooms.quad.pricePerPax.exchange.currency.value",
        "rooms.quad.amountPricePerPax.value",
        "rooms.quad.amountPricePerPax.currency.label",
        "rooms.quad.amountPricePerPax.currency.symbol",
        "rooms.quad.amountPricePerPax.currency.value",
        "rooms.quad.amountPricePerPax.exchange.value",
        "rooms.quad.amountPricePerPax.exchange.currency.label",
        "rooms.quad.amountPricePerPax.exchange.currency.symbol",
        "rooms.quad.amountPricePerPax.exchange.currency.value",
        "rooms.quad.pvpAffiliatePerPax.value",
        "rooms.quad.pvpAffiliatePerPax.currency.label",
        "rooms.quad.pvpAffiliatePerPax.currency.symbol",
        "rooms.quad.pvpAffiliatePerPax.currency.value",
        "rooms.quad.pvpAffiliatePerPax.exchange.value",
        "rooms.quad.pvpAffiliatePerPax.exchange.currency.label",
        "rooms.quad.pvpAffiliatePerPax.exchange.currency.symbol",
        "rooms.quad.pvpAffiliatePerPax.exchange.currency.value",
        "children",
        "netPrice.value",
        "netPrice.currency.label",
        "netPrice.currency.symbol",
        "netPrice.currency.value",
        "netPrice.exchange.value",
        "netPrice.exchange.currency.label",
        "netPrice.exchange.currency.symbol",
        "netPrice.exchange.currency.value",
        "amount.value",
        "amount.currency.label",
        "amount.currency.symbol",
        "amount.currency.value",
        "amount.exchange.value",
        "amount.exchange.currency.label",
        "amount.exchange.currency.symbol",
        "amount.exchange.currency.value",
        "pvpAffiliate.value",
        "pvpAffiliate.currency.label",
        "pvpAffiliate.currency.symbol",
        "pvpAffiliate.currency.value",
        "pvpAffiliate.exchange.value",
        "pvpAffiliate.exchange.currency.label",
        "pvpAffiliate.exchange.currency.symbol",
        "pvpAffiliate.exchange.currency.value",
        "cancelled.cancelDate",
        "cancelled.user",
        "cancelled.byTraveler",
        "cancelled.reason",
        "createdOn",
        "updatedOn",
        "__v"
    ],
    Roles: [
        "_id",
        "title",
        "slug",
        "permissions",
        "publishedDate",
        "description",
        "createdOn",
        "updatedOn",
        "__v"
    ],
    Sequences: [
        "_id",
        "name",
        "slug",
        "publishedDate",
        "mainindex",
        "productindex",
        "queryindex",
        "bookingindex",
        "createdOn",
        "updatedOn",
        "__v"
    ],
    Stories: [
        "_id",
        "code",
        "modelrelated",
        "storytype",
        "parentid",
        "date",
        "user",
        "story",
        "createdOn",
        "updatedOn",
        "__v"
    ],
    Payments: [
        "_id",
        "code",
        "action",
        "payment",
        "paymentmethod",
        "paymentarget",
        "receiptnumber",
        "transferid",
        "date",
        "validatedate",
        "nextpaymentdate",
        "payabledate",
        "amount",
        "currency.label",
        "currency.symbol",
        "currency.value",
        "booking",
        "createdOn",
        "updatedOn",
        "slug",
        "__v"
    ],
    Invoices: [
        "_id",
        "name",
        "slug",
        "code",
        "date",
        "invoicenumber",
        "file",
        "city",
        "cp",
        "idnumber",
        "taxinvoice",
        "address",
        "country.name_es",
        "country.name",
        "country.countrycode",
        "booking",
        "createdOn",
        "updatedOn",
        "__v"
    ],
    Hevents: [
        "_id",
        "code",
        "slug",
        "subject",
        "action",
        "delivereddate",
        "state",
        "createdonindexing",
        "data",
        "createdOn",
        "updatedOn",
        "__v"
    ],
    SubscriptionMessages: [
        "_id",
        "code",
        "slug",
        "subject",
        "action",
        "lasterrordate",
        "commitdate",
        "createdonindexing",
        "subscribertaskdone",
        "state",
        "subscriberslist",
        "errorslist",
        "lastparams",
        "lastresults",
        "createdOn",
        "updatedOn",
        "__v"
    ],
    Travelers: [
        "_id",
        "code",
        "firstname",
        "lastname",
        "slug",
        "phone",
        "email",
        "skype",
        "sendmenews",
        "dateofbirth",
        "location.fulladdress",
        "location.city",
        "location.stateorprovince",
        "location.cp",
        "location.country",
        "location.countrycode",
        "location.continent",
        "location.latitude",
        "location.longitude",
        "cif",
        "nif",
        "accountingnumber",
        "description",
        "membershipDate",
        "images.photo.public_id",
        "images.photo.version",
        "images.photo.signature",
        "images.photo.format",
        "images.photo.resource_type",
        "images.photo.url",
        "images.photo.width",
        "images.photo.height",
        "images.photo.secure_url",
        "images.logo.public_id",
        "images.logo.version",
        "images.logo.signature",
        "images.logo.format",
        "images.logo.resource_type",
        "images.logo.url",
        "images.logo.width",
        "images.logo.height",
        "images.logo.secure_url",
        "images.splash.public_id",
        "images.splash.version",
        "images.splash.signature",
        "images.splash.format",
        "images.splash.resource_type",
        "images.splash.url",
        "images.splash.width",
        "images.splash.height",
        "images.splash.secure_url",
        "user",
        "currency.label",
        "currency.symbol",
        "currency.value",
        "timeZone.gmtAdjustment",
        "timeZone.label",
        "timeZone.timeZoneId",
        "timeZone.useDaylightTime",
        "timeZone.value",
        "createdOn",
        "updatedOn",
        "__v"
    ],
    UserQueries : [
        "_id",
        "title",
        "slug",
        "name",
        "code",
        "travelercode",
        "affiliatecode",
        "publishedDate",
        "createdonindexing",
        "startdateindexing",
        "destinationsindexing",
        "destinationsindexingen",
        "stateindexing",
        "holderindexing",
        "titleindexing",
        "affiliateindexing",
        "description",
        "idBooking",
        "additionalinfo.description",
        "additionalinfo.trip",
        "additionalinfo.regimen",
        "additionalinfo.needs",
        "additionalinfo.guide.included",
        "additionalinfo.guide.language.spanish",
        "additionalinfo.guide.language.english",
        "additionalinfo.guide.language.french",
        "additionalinfo.guide.language.german",
        "additionalinfo.guide.language.italian",
        "additionalinfo.guide.language.portuguese",
        "dates.knowingdates",
        "dates.arrivaldate",
        "dates.arrival.year",
        "dates.arrival.month",
        "dates.arrival.monthname_es",
        "dates.arrival.monthname_en",
        "dates.arrival.day",
        "dates.month.monthnumber",
        "dates.month.monthname",
        "dates.month.monthyear",
        "dates.week",
        "dates.alreadygotflights",
        "dates.dataflightsIn",
        "dates.dataflightsOut",
        "dates.duration",
        "dates.flexibility.number",
        "dates.flexibility.range",
        "hosting.hostingKind",
        "hosting.hostingKindNotes",
        "hosting.lowcosthotels",
        "hosting.standarhotels",
        "hosting.superiorhotels",
        "hosting.charmhotels",
        "hosting.luxuryhotels",
        "budget.cost",
        "budget.currency.label",
        "budget.currency.symbol",
        "budget.currency.value",
        "budget.showmebestprices",
        "group.typeGroup",
        "group.adults",
        "group.comments",
        "group.rooms.single",
        "group.rooms.double",
        "group.rooms.triple",
        "quotes",
        "traveler",
        "affiliate",
        "dmcs",
        "chats",
        "state",
        "affiliateuser",
        "quotesstates",
        "destinations",
        "cancelled.cancelDate",
        "cancelled.user",
        "cancelled.byTraveler",
        "cancelled.reason",
        "whattodo",
        "roomDistribution",
        "historic",
        "comments",
        "passengers",
        "createdOn",
        "updatedOn",
        "__v"
    ],
    OMTAdmin: [
        "_id",
        "code",
        "name",
        "slug",
        "email",
        "skype",
        "location.fulladdress",
        "location.city",
        "location.stateorprovince",
        "location.cp",
        "location.country",
        "location.countrycode",
        "location.continent",
        "location.latitude",
        "location.longitude",
        "description",
        "membershipDate",
        "images.photo.public_id",
        "images.photo.version",
        "images.photo.signature",
        "images.photo.format",
        "images.photo.resource_type",
        "images.photo.url",
        "images.photo.width",
        "images.photo.height",
        "images.photo.secure_url",
        "images.logo.public_id",
        "images.logo.version",
        "images.logo.signature",
        "images.logo.format",
        "images.logo.resource_type",
        "images.logo.url",
        "images.logo.width",
        "images.logo.height",
        "images.logo.secure_url",
        "images.splash.public_id",
        "images.splash.version",
        "images.splash.signature",
        "images.splash.format",
        "images.splash.resource_type",
        "images.splash.url",
        "images.splash.width",
        "images.splash.height",
        "images.splash.secure_url",
        "user",
        "createdOn",
        "updatedOn",
        "__v"
    ],
    Flights: [
        "_id",
        "itinerary.itinerariesId",
        "itinerary.priceGroup",
        "itinerary.token",
        "itinerary.numAdult",
        "itinerary.numChild",
        "itinerary.numInfant",
        "itinerary.price",
        "itinerary.slug",
        "locator",
        "reference",
        "idBooking",
        "flight",
        "booking",
        "createdOn",
        "updatedOn",
        "slug",
        "__v"
    ],
    Users: [
        "_id",
        "username",
        "email",
        "code",
        "phone",
        "photo.public_id",
        "photo.version",
        "photo.signature",
        "photo.format",
        "photo.resource_type",
        "photo.url",
        "photo.width",
        "photo.height",
        "photo.secure_url",
        "password",
        "isDMC",
        "isTraveler",
        "isAdmin",
        "isAffiliate",
        "roles",
        "active",
        "isLocal",
        "isFacebookLinked",
        "isTwitterLinked",
        "isGoogleLinked",
        "apikey",
        "facebook.id",
        "facebook.token",
        "facebook.email",
        "facebook.name",
        "facebook.link",
        "twitter.id",
        "twitter.token",
        "twitter.displayName",
        "twitter.username",
        "twitter.link",
        "google.id",
        "google.token",
        "google.email",
        "google.name",
        "google.link",
        "timeZone.ObjectgmtAdjustment",
        "timeZone.label",
        "timeZone.timeZoneId",
        "timeZone.useDaylightTime",
        "timeZone.value",
        "currency.label",
        "currency.symbol",
        "currency.value",
        "createdOn",
        "updatedOn",
        "__v"
    ]
};
var getfields = module.exports.getfields = function (core, modelname) {
   return Object.keys(core.dbconnections.items.mongodb.models[modelname].schema.paths)
}

module.exports.schemadefaultbehaviour = {
    OMTAdmin: {
        description: 'Clase miembro administrador',
        name: 'OMTAdmin',
        maxresults: 50,
        offset: 50,
        populate: [{ path: 'user' }],
        fields: {
            get: function (core) { return getfields(core, 'OMTAdmin') },
            default: schemafields['OMTAdmin'],
            common: '*'
        },
        roles: [
            { role: 'admin', permission: '*' },
            { role: 'affiliate', permission: 'none' },
            { role: 'dmc', permission: 'none' },
            { role: 'traveler', permission: 'none' }]
    },
    Affiliate: {
        description: 'Clase miembro afiliado/agencia',
        name: 'Affiliate',
        maxresults: 50,
        offset: 50,
        populate: [{ path: 'user' }, { path: 'wlcustom' }],
        fields: {
            get: function (core) { return getfields(core, 'Affiliate') },
            default: schemafields['Affiliate'],
            common: '*'
        },
        roles: [
            { role: 'admin', permission: '*' },
            { role: 'affiliate', permission: 'self' },
            { role: 'dmc', permission: 'none' },
            { role: 'traveler', permission: 'none' }],
        selfqueryfield: '_id',
        selfquery: function (id, rolename) {
            var filt = { affiliate: { _id: id } };
            return filt[rolename];
        }
    },
    BookedProducts: {
        description: 'Model para Productos reservados, es un snapshot del producto en el momento de la reserva',
        name: 'BookedProducts',
        maxresults: 50,
        offset: 50,
        populate: [
            { path: 'dmc' }, { path: 'departurecity' }, { path: 'stopcities' },
            { path: 'sleepcity' }, { path: 'departurecountry' }, { path: 'stopcountry' },
            { path: 'sleepcountry' }],
        fields: {
            get: function (core) { return getfields(core, 'BookedProducts') },
            default: schemafields['BookedProducts'],
            common: '*'
        },
        roles: [
            { role: 'admin', permission: '*' },
            { role: 'affiliate', permission: '*' },
            { role: 'dmc', permission: 'self' },
            { role: 'traveler', permission: 'none' }],
        selfqueryfield: '_id',
        selfquery: function (id, rolename) {
            var filt = { dmc: { dmc: id } };
            return filt[rolename];
        }
    },
    Bookings: {
        description: 'Model para reservas - progresivamente en desuso',
        name: 'Bookings',
        maxresults: 50,
        offset: 50,
        populate: [
            { path: 'productDmc' }, { path: 'dmc' }, { path: 'traveler' },
            { path: 'affiliate' }],
        fields: {
            get: function (core) { return getfields(core, 'Bookings') },
            default: schemafields['Bookings'],
            common: '*'
        },
        roles: [
            { role: 'admin', permission: '*' },
            { role: 'affiliate', permission: 'self' },
            { role: 'dmc', permission: 'self' },
            { role: 'traveler', permission: 'self' }],
        selfqueryfield: '_id',
        selfquery: function (id, rolename) {
            var filt = {
                affiliate: { affiliate: id },
                dmc: { dmc: id },
                traveler: { traveler: id }
            };
            return filt[rolename];
        }
    },
    Bookings2: {
        description: 'Model para reservas',
        name: 'Bookings2',
        maxresults: 50,
        offset: 50,
        populate: [
            { path: 'products' }, { path: 'dmc' }, { path: 'traveler' },
            { path: 'affiliate' }, { path: 'query' }, { path: 'quote' },
            { path: 'payments' }, { path: 'stories' }, { path: 'signin' },
            { path: 'invoices' }, { path: 'relatedbooking' }],
        fields: {
            get: function (core) { return getfields(core, 'Bookings2') },
            default: schemafields['Bookings2'],
            common: '*'
        },
        roles: [
            { role: 'admin', permission: '*' },
            { role: 'affiliate', permission: 'self' },
            { role: 'dmc', permission: 'self' },
            { role: 'traveler', permission: 'self' }],
        selfqueryfield: '_id',
        selfquery: function (id, rolename) {
            var filt = {
                affiliate: { affiliate: id },
                dmc: { dmc: id },
                traveler: { traveler: id }
            };
            return filt[rolename];
        }
    },
    Chats: {
        description: 'Model para chats - presente en bookings y taylormade',
        name: 'Chats',
        maxresults: 50,
        offset: 50,
        populate: [
            { path: 'userquery' }, { path: 'booking' }, { path: 'quote' },
            { path: 'traveler' }, { path: 'dmc' }, { path: 'affiliate' }],
        fields: {
            get: function (core) { return getfields(core, 'Chats') },
            default: schemafields['Chats'],
            common: '*'
        },
        roles: [
            { role: 'admin', permission: '*' },
            { role: 'affiliate', permission: 'self' },
            { role: 'dmc', permission: 'self' },
            { role: 'traveler', permission: 'self' }],
        selfqueryfield: '_id',
        selfquery: function (id, rolename) {
            var filt = {
                affiliate: { affiliate: id },
                dmc: { dmc: id },
                traveler: { traveler: id }
            };
            return filt[rolename];
        }
    },
    DestinationCities: {
        description: 'Model para cities - es una vista de la coleccion cities en cms-openmarket',
        name: 'DestinationCities',
        populate: [{ path: 'country' }],
        maxresults: 300,
        offset: 300,
        fields: {
            get: function (core) { return getfields(core, 'DestinationCities') },
            default: schemafields['DestinationCities'],
            common: '*'
        },
        roles: [
            { role: 'admin', permission: '*' },
            { role: 'affiliate', permission: '*' },
            { role: 'dmc', permission: '*' },
            { role: 'traveler', permission: '*' }]
    },
    DestinationCountries: {
        description: 'Model para countries - es una vista de la coleccion countries en cms-openmarket',
        name: 'DestinationCountries',
        populate: [{ path: 'zone' }],
        maxresults: 300,
        offset: 300,
        fields: {
            get: function (core) { return getfields(core, 'DestinationCountries') },
            default: schemafields['DestinationCountries'],
            common: '*'
        },
        roles: [
            { role: 'admin', permission: '*' },
            { role: 'affiliate', permission: '*' },
            { role: 'dmc', permission: '*' },
            { role: 'traveler', permission: '*' }]
    },
    DestinationCountriesZones: {
        description: 'Model para zones - es una vista de la coleccion zones en cms-openmarket',
        name: 'DestinationCountriesZones',
        populate: null,
        maxresults: 300,
        offset: 300,
        fields: {
            get: function (core) { return getfields(core, 'DestinationCountriesZones') },
            default: schemafields['DestinationCountriesZones'],
            common: '*'
        },
        roles: [
            { role: 'admin', permission: '*' },
            { role: 'affiliate', permission: '*' },
            { role: 'dmc', permission: '*' },
            { role: 'traveler', permission: '*' }]
    },
    DMCs: {
        description: 'Model para DMCs - proveedores de servicios/products',
        name: 'DMCs',
        maxresults: 50,
        offset: 50,
        populate: [{ path: 'contactuser' }, { path: 'user' }, { path: 'admin' }],
        fields: {
            get: function (core) { return getfields(core, 'DMCs') },
            default: schemafields['DMCs'],
            common: '*'
        },
        roles: [
            { role: 'admin', permission: '*' },
            { role: 'affiliate', permission: '*' },
            { role: 'dmc', permission: '*' },
            { role: 'traveler', permission: '*' }]
    },
    DMCProducts: {
        description: 'Model para Produts DMC - Products de DMC/TaylorMade',
        name: 'DMCProducts',
        maxresults: 50,
        offset: 50,
        populate: [
        { path: 'dmc' }, { path: 'departurecity' }, { path: 'stopcities' },
        { path: 'sleepcity' }, { path: 'departurecountry' }, { path: 'stopcountry' },
        { path: 'sleepcountry' }],
        fields: {
            get: function (core) { return getfields(core, 'DMCProducts') },
            default: schemafields['DMCProducts'],
            common: '*'
        },
        roles: [
            { role: 'admin', permission: '*' },
            { role: 'affiliate', permission: '*' },
            { role: 'dmc', permission: 'self' },
            { role: 'traveler', permission: '*' }],
        selfqueryfield: '_id',
        selfquery: function (id, rolename) {
            var filt = {
                dmc: { dmc: id }
            };
            return filt[rolename];
        }
    },
    Invoices: {
        description: 'Model para Produts Invoices - Facturas, presentes en Booking',
        name: 'Invoices',
        maxresults: 100,
        offset: 100,
        populate: [{ path: 'booking' }],
        fields: {
            get: function (core) { return getfields(core, 'Invoices') },
            default: schemafields['Invoices'],
            common: '*'
        },
        roles: [
            { role: 'admin', permission: '*' },
            { role: 'affiliate', permission: 'self' },
            { role: 'dmc', permission: 'self' },
            { role: 'traveler', permission: 'none' }],
        selfqueryfield: '_id',
        selfquery: function (id, rolename) {
            var filt = {
                affiliate: { affiliate: id },
                dmc: { dmc: id }
            };
            return filt[rolename];
        }
    },
    Stories: {
        description: 'Model para Stories - Historias de usuario, booking ... storytype indica el si se trata de historio o comentario',
        name: 'Stories',
        maxresults: 100,
        offset: 100,
        populate: function (story) {
            var st = story;
            if (Array.isArray(story)) {
                st = story != null && story.length > 0 ? story[0] : null;
            } 
            var rs = st != null ? [{ path: 'parentid', model: st.modelrelated }] : null;
            return rs;
        },
        fields: {
            get: function (core) { return getfields(core, 'Stories') },
            default: schemafields['Stories'],
            common: '*'
        },
        roles: [
            { role: 'admin', permission: '*' },
            { role: 'affiliate', permission: 'self' },
            { role: 'dmc', permission: 'self' },
            { role: 'traveler', permission: 'none' }],
        selfqueryfield: '_id',
        selfquery: function (id, rolename) {
            var filt = {
                affiliate: { parentid: id },
                dmc: { parentid: id }
            };
            return filt[rolename];
        }
    },
    Payments: {
        description: 'Model para Pagos/Cobros - action indica si se trata de un cobro(charge) o un pago(pay)',
        name: 'Payments',
        populate: [{ path: 'booking' }],
        maxresults: 200,
        offset: 200,
        fields: {
            get: function (core) { return getfields(core, 'Payments') },
            default: schemafields['Payments'],
            common: '*'
        },
        roles: [
            { role: 'admin', permission: '*' },
            { role: 'affiliate', permission: 'self' },
            { role: 'dmc', permission: 'self' },
            { role: 'traveler', permission: 'self' }],
        selfqueryfield: '_id',
        selfquery: function (id, rolename) {
            var filt = {
                affiliate: { booking: id },
                dmc: { booking: id },
                traveler: { booking: id }
            };
            return filt[rolename];
        }
    },
    Quotes: {
        description: 'Model para Quotes - respuesta de un DMC a una Query o TaylorMade',
        name: 'Quotes',
        maxresults: 50,
        offset: 50,
        populate: [{ path: 'chat' }, { path: 'products' }],
        fields: {
            get: function (core) { return getfields(core, 'Quotes') },
            default: schemafields['Quotes'],
            common: '*'
        },
        roles: [
            { role: 'admin', permission: '*' },
            { role: 'affiliate', permission: '*' },
            { role: 'dmc', permission: 'self' },
            { role: 'traveler', permission: 'self' }],
        selfqueryfield: '_id',
        selfquery: function (id, rolename) {
            var filt = {
                affiliate: { affiliate: id },
                dmc: { dmc: id },
                traveler: { traveler: id }
            };
            return filt[rolename];
        }
    },
    Roles: {
        description: 'Model para Roles - Rol de usuario, indica si es Admin, Traveler, Affiliate  o DMC',
        name: 'Roles',
        maxresults: 500,
        offset: 500,
        populate: [{ path: 'permissions' }],
        fields: {
            get: function (core) { return getfields(core, 'Roles') },
            default: schemafields['Roles'],
            common: '*'
        },
        roles: [
            { role: 'admin', permission: '*' },
            { role: 'affiliate', permission: 'none' },
            { role: 'dmc', permission: 'none' },
            { role: 'traveler', permission: 'none' }]
    },
    Travelers: {
        description: 'Model para Traveler - Viajeros/Clientes/Usuarios de plataform B2C (omt)',
        name: 'Travelers',
        maxresults: 150,
        offset: 150,
        populate: [{ path: 'user' }],
        fields: {
            get: function (core) { return getfields(core, 'Travelers') },
            default: schemafields['Travelers'],
            common: '*'
        },
        roles: [
            { role: 'admin', permission: '*' },
            { role: 'affiliate', permission: 'none' },
            { role: 'dmc', permission: 'none' },
            { role: 'traveler', permission: 'self' }],
        selfqueryfield: '_id',
        selfquery: function (id, rolename) {
            var filt = {
                traveler: { _id: id }
            };
            return filt[rolename];
        }
    },
    UserQueries: {
        description: 'Model para Queries - Estructura para peticiones Taylor Made (OMT y YTO)',
        name: 'UserQueries',
        maxresults: 50,
        offset: 50,
        populate: [
        { path: 'quotes' }, { path: 'traveler' }, { path: 'affiliate' },
        { path: 'dmcs' }, { path: 'chats' }],
        fields: {
            get: function (core) { return getfields(core, 'UserQueries') },
            default: schemafields['UserQueries'],
            common: '*'
        },
        roles: [
            { role: 'admin', permission: '*' },
            { role: 'affiliate', permission: 'self' },
            { role: 'dmc', permission: 'self' },
            { role: 'traveler', permission: 'self' }],
        selfqueryfield: '_id',
        selfquery: function (id, rolename) {
            var filt = {
                affiliate: { affiliate: id },
                dmc: { dmc: id },
                traveler: { traveler: id }
            };
            return filt[rolename];
        }
    },
    Users: {
        description: 'Model para Usuarios - Clase base/no abstracta que heredan todos los miembros (Affiliate, Traveler, OMTAdmin, DMC)',
        name: 'Users',
        maxresults: 500,
        offset: 500,
        populate: [{ path: 'roles', populate: 'permissions' }],
        fields: {
            get: function (core) { return getfields(core, 'Users') },
            default: schemafields['Users'],
            common: '*'
        },
        roles: [
            { role: 'admin', permission: '*' },
            { role: 'affiliate', permission: 'sample' },
            { role: 'dmc', permission: 'sample' },
            { role: 'traveler', permission: 'none' }]
    },
    WLCustomizations: {
        description: 'Model para White label personalizacion - contiene los ajustes de personalizacion de marcablanca',
        name: 'Users',
        maxresults: 500,
        offset: 500,
        populate: [{ path: 'roles', populate: 'permissions' }],
        fields: {
            get: function (core) { return getfields(core, 'Users') },
            default: schemafields['Users'],
            common: '*'
        },
        roles: [
            { role: 'admin', permission: '*' },
            { role: 'affiliate', permission: '*' },
            { role: 'dmc', permission: '*' },
            { role: 'traveler', permission: '*' }],
        selfqueryfield: 'code',
        selfquery: function (id, rolename) {
            var filt = {
                code: { code: id },
            };
            return filt[rolename];
        }
    }
}