<div class="modificar-busqueda-wrap visible-xs visible-sm bg-darkblue" ng-cloak>
  <div class="container">
    <div class="modificar-busqueda row pt-xl pb-xl">
      <div class="col-sm-5 modificar-busqueda-toggle text-light">
          <a class="btn btn-empty" ng-click="buscadorcollapsed = !buscadorcollapsed" href="#"> <i class="fa fa-search"></i> Modificar búsqueda</a>
      </div>
    </div>
    </div>
</div>