<section class="max-center-sm">
   <div class="info-block well">
    <div class="row">
      
      <div class="col-md-12">
        <h3 class="mt-zero pt-zero text-center"><strong>¿Necesitas Ayuda?</strong><br><br><span class="text-gray">Llámanos.</span></h3>
        <h3 class="bold mt-zero pt-zero text-center"><i class="fa fa-phone"></i> {% if brand && brand.phone %}{? brand.phone ?}{% else %} 971 902 426{% endif %}</h3>
      </div>
    </div>
   </div>
</section>