<div class="list-group" ng-controller="affiliateContentMenuCtrl">
  <a href="/pagina/ventajas-agencia" target="_self" class="list-group-item" ng-class="getClass('/pagina/ventajas-agencia')">Ventajas Agencia</a>
  <a href="/pagina/soluciones-de-distribucion" target="_self" class="list-group-item" ng-class="getClass('/pagina/soluciones-de-distribucion')">Soluciones de distribución</a>
  <a href="/pagina/programas-multidays" target="_self" class="list-group-item" ng-class="getClass('/pagina/programas-multidays')">Programas Multidays</a>
  <a href="/pagina/viajes-a-medida" target="_self" class="list-group-item" ng-class="getClass('/pagina/viajes-a-medida')">Viajes a Medida</a>
  <a href="/pagina/receptivos" target="_self" class="list-group-item" ng-class="getClass('/pagina/receptivos')">Receptivos</a>
</div>